spring.datasource.url=jdbc:mariadb://yh-rds.cr4so20imjnv.ap-northeast-2.rds.amazonaws.com:3306/minbak_db
spring.datasource.username=devuser
spring.datasource.password=zEjgXQV6ys
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.thymele.cache=false

logging.level.sql=debug
logging.level.org.mybatis=debug